### ISSUE TITLE
VR creator with limited amount of CLI experience

### ISSUE THREAD

**Issue by lolo2k** [hyperlogic/splatapult#10]
Hi,

My name is Lolo, and I would love to use your VR viewer to demo my 3DGS scenes.
But my knowlage of CLI is limited and installing a project like this from GitHub without a detailed install tutorial has been tried, and failed....
I understand that a lot of people are able to "install" this but i'm simply not able to look at this repo and go, yeah this, then that then boom!
I have watched a ton of tutorials to learn how to install Nvidia Nerf, Nerfstudio, Inria GS but with a lot of hand holding. And now that i'm trying to simply download, place on HD and execute a command in CLI i'm completly lost. Also because of the custom prompt you are using in the youtube video.
Would you mind doing an install video for dummies like me? or is there another way i can learn how to install your project? Because i really like what i see in the Youtube video and i'd really love to try!

Thank you for your patience.

Lodewijk

**Comment by hyperlogic** [comment]
Hi, yeah the github project is more about the source code.  It doesn't provide a running executable, unless you build it from scratch.  I hope to address this at a later date.

First off you'll need some data.  I recommend downloading .ply created using the [Luma App](https://lumalabs.ai/).
Lets say the file you downloaded is `c:\data\my_capture.ply`

But in the meantime, you can download a Windows executable [here](https://hyperlogic.github.io/files/splatapult-0.1-x64.zip).
Unzip that folder somewhere on your hard drive.  Sadly, you can't just double click it to run.  Instead you'll have to open a CLI in that folder.  Also, you should [cd](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/) into the same directory that you've unzipped the zip file.  Once there type `splatapult.exe c:\data\my_capture.ply`

Hope this helps.
