### ISSUE TITLE
Quest 3: VR head not working

### ISSUE THREAD

**Issue by lolo2k** [hyperlogic/splatapult#11]
Hi, Thanks for helping me open and install splatapult.
Now that it is running on my system I'm trying to get it to work in VR.
I have opended it with oculus link running and with Steam VR running but I keep getting:

C:\Users\lodew\splatapult>splatapult.exe -v C:\Users\lodew\ansel\mmemBLENDERexport.ply
[ERROR] xrCreateSession [XR_ERROR_GRAPHICS_DEVICE_INVALID]
[ERROR] OpenXR Init failed
[ERROR] App::Init failed
 
I have tryed many times, yet can't get it to project and track my headset.
Thanks for the help.

Lolo

**Comment by hyperlogic** [comment]
You need to explicitly set the OpenXR runtime.  If you're using the link cable on a Meta/Oculus headset, the best approach is to go into the Oculus app settings (on your PC), and enable the OpenXR runtime there.

![image](https://github.com/hyperlogic/splatapult/assets/20499/d193adcc-82db-4d5b-87f1-0fff49ebce4e)

Hope this helps.

**Comment by hyperlogic** [comment]
Let me know if you are still experiencing this problem after setting your OpenXR runtime.
