### ISSUE TITLE
Qestion about quantizedZs value in presort_compute.glsl

### ISSUE THREAD

**Issue by yuyaolong** [hyperlogic/splatapult#15]
looks depth is -Zeye here, rang is [near, far]
so is the correspond fixedPointZ here rang  [uint32_max, 0]?
https://github.com/hyperlogic/splatapult/blob/d985c9f569e5e4cefafd3762017f6c3c2790cd06/shader/presort_compute.glsl#L53

which means closer object with higher fixedPointZ value?

**Comment by yuyaolong** [comment]
Again, Thanks for answering.
My follow-up question is why we need to range splat from back to front?
is it because of color correction of the alpha blending needs to be rendered from the back splats?
In the beginning, I thought we can save computation if we range spalts from front to back with depth enabled. But it looks not the case for now.

**Comment by hyperlogic** [comment]
To get a correct looking image the transparencies must be correct. It might be possible in software to evaluate the volume equation directly, but that would be much too slow for real-time rendering.  The typical approach for hardware rendering is to layer transparencies into the color buffer by rendering them in back to front order.

>  I thought we can save computation if we range spalts from front to back with depth enabled
Most of the area for each splat is transparent, so using the depth buffer would block many splats that contribute to the final color for each pixel.
