### ISSUE TITLE
VR seems distorted compared to normal render

### ISSUE THREAD

**Issue by JorisGoosen** [hyperlogic/splatapult#18]
Hey, first of, thanks for making this!

I am trying to make a model out of some stuff here on my table. Ive been running into all sorts of issues with the StfM part.
But thought I got that working by now. 

However, while the render on the desktop look "perfectly" ok (in the sense that for instance the amanite mushrooms have sort of the same shape as in reality):
<img width="1027" alt="image" src="https://github.com/hyperlogic/splatapult/assets/29062713/b7f83262-85fc-43c3-9ad5-0f098e636921">

The render in vr looks weirdly diagonal/compressed/something?
I guess this is something in splatapult given that the desktop render seems ok?
![20240706131442_1](https://github.com/hyperlogic/splatapult/assets/29062713/b31799d2-6e6c-46c6-adfb-147ce2479a51)
![20240706131442_1_vr](https://github.com/hyperlogic/splatapult/assets/29062713/f0c91001-cb04-4d0b-926d-0f46717e9880)

The VR looks a bit more slanted in the VR glasses btw

**Comment by JorisGoosen** [comment]
Btw, I did not have this with other reconstructions from colmap. This seems to happen specifically with the "undistorted" images and reconstruction. This because the camera model that I need in colmap for actual feature matching is not supported in splatapult

**Comment by hyperlogic** [comment]
Hey, I think this might be an issue with openxr support, rather then anything wrong with your data.  What headset are you using? Also, which openxr runtime are you using? are you running using Oculus App, or SteamVR?

Can you run with the -d flag on the command line?  that will print out some info that might help me debug this.  can you attach that output to this ticket?

**Comment by JorisGoosen** [comment]
Hmm, you are probably right. 
Im using a valve index with steamvr.

But as I was running it now it seems to have fixed itself... 
The same model that was giving me problems before now seems good.
So I guess Ill close this issue. If the problems return Ill make sure to get the debug output immediately.
