### ISSUE TITLE
Gaussian splats a mirrored along ground plane

### ISSUE THREAD

**Issue by Vertexwahn** [hyperlogic/splatapult#20]
Gaussian splats a mirrored along ground plane

In other viewers (etc. SIBR) they look correct

Is there an option to mirror / invert along y-axis?

**Comment by hyperlogic** [comment]
Thanks for the report, however, I've never encountered this problem before, w.r.t. mirroring.  You can use the q and e keys to roll the camera if it is upside down.  Can you provide screenshots, or even better the ply file that is giving you this issue?

**Comment by hyperlogic** [comment]
Feel free to re-open this issue, if you continue to have this problem.
