### ISSUE TITLE
Failed to load vertex shader

### ISSUE THREAD

**Issue by omigeot** [hyperlogic/splatapult#22]
Built on Ubuntu 24.04, the lastest commit (d05e3699384f82c7f12a8dfaadae244658aababe) fails with the following error : 

> $ ./splatapult data/test.ply 
> [ERROR] Failed to load vertex shader shader/debugdraw_vert.glsl
> [ERROR] Error loading DebugRenderer shader!
> [ERROR] DebugRenderer Init failed
> [ERROR] App::Init failed

**Comment by hyperlogic** [comment]
The splatapult executable expects to find the font, shader & texture directories.  If you build without the cmake -DSHIPPING flag it checks the parent dir to find them.  This is convenient when using a build folder one level under the main dir.   However if you do add the -DSHIPPING flag, it will search the current dir.

hope this helps.

**Comment by omigeot** [comment]
That was is, thanks alot :)
