### ISSUE TITLE
DEPTH_TEST issues on Android

### ISSUE THREAD

**Issue by wanfengnianhua** [hyperlogic/splatapult#25]
What is the reason why the code was ported to Android with depth testing and rendered as bubbles？
![image](https://github.com/user-attachments/assets/01aa990f-514a-41f7-97a1-c945fe24e0f5)

rendering：
![20240827-134117](https://github.com/user-attachments/assets/f03d74f3-c6fa-4bbf-b5bc-655d3a7c7e43)

**Comment by hyperlogic** [comment]
Hi, the android port was only tested on oculus quest and is likely out of date.  Apologies, I'm not sure what the cause of the rendering issues you are seeing are.  It could be that the shader compilation failed for OpenGLES.

Do you have any output logs? that might help debug the issue.

**Comment by wanfengnianhua** [comment]
It has been resolved, it is due to an issue with the accuracy of the presort_compute float

**Comment by wanfengnianhua** [comment]
![image](https://github.com/user-attachments/assets/ed6ae1da-04a2-4ac1-a969-4914af531d96)
I have added a new model matrix, but the processed colors are not full. How can I synchronize and change the shader? Can you give me some guidance?
【Before】
![img_v3_02ej_7af2f2e1-ac0c-4f5b-993e-de84afb92f7g](https://github.com/user-attachments/assets/2606247d-4228-42d8-bc6f-44e30c279a4b)
【After】
![img_v3_02ej_089b1a03-619b-4f72-9d98-2aa2a0f290ag](https://github.com/user-attachments/assets/4fc9b0f0-3107-400d-bde6-9c9286bb1020)

**Comment by wanfengnianhua** [comment]
resolved

**Comment by brisyramshere** [comment]
你好 请问这个工程你现在成功在安卓上编译并且渲染成功了吗？这里面是否有什么坑？
