### ISSUE TITLE
Error on loading files

### ISSUE THREAD

**Issue by fasteinke** [hyperlogic/splatapult#3]
Thanks for putting this alternative viewer out! And, trying the splatapult-0.1-x64.zip release ...

But, I had to try multiple PLY files before a model was successfully read; and that was one with the truck.

What occurs nearly every time are multiple instances of a message like

[ERROR] Error parsing ply file "D:\Apps\GaussianSplatting\splats\Colab\bicycle\b4000.ply", missing f_rest property

**Comment by hyperlogic** [comment]
Interesting, that b4000.ply file is missing the spherical harmonics data.  Is it just points?  What tool did you use to create that ply file?  Can you attach it to this issue? If it's not too large.

**Comment by fasteinke** [comment]
Need to check it more carefully, but the majority of PLYs come from using a modified Colab notebook, created by camenduru. Also, a selection from Polycam and Luma processing.

None of the other viewers I've tried have complained, at any time. Anyway, will look to organising a super small PLY showing the issue, and attach.

**Comment by hyperlogic** [comment]
Thanks, for attaching the ply.  I didn't have any PLY files without spherical harmonics to test on.  Should be fixed if you re-download the splatapult-0.1-x64.zip file
