### ISSUE TITLE
Is it possible for me to compile and deploy this project on an ordinary mobile phone to achieve the deployment of the gs model on the mobile phone?

### ISSUE THREAD

**Issue by brisyramshere** [hyperlogic/splatapult#30]

**Comment by hyperlogic** [comment]
At the moment this project is not set up for mobile development, however there was some experimental work done for Meta Quest which is an Android based OS.  It might be possible to follow the pattern of android_main.cpp and get an Android build working.

The Android build would rely on OpenGLES3.1 for rendering. Apple devices, on the other hand, do not support OpenGLES for rendering.  So the rendering code would have to be converted to the Metal API.
