### ISSUE TITLE
2D GS support!

### ISSUE THREAD

**Issue by chenqi13814529300** [hyperlogic/splatapult#32]
Your work is great, and I hope this renderer can add 2D Gaussian rendering functionality. Can you please add it or give me some guidance on how to add this feature.

**Comment by hyperlogic** [comment]
Good feature request, not sure I can get to it anytime soon.  My understanding tho is that 2DGS is a special case of 3DGS, it might be possible to just set the scale factor of the 3DGS to be zero (0.00001) along one dimension, and the existing 3DGS renderer *should* just work.  However I don't think this would be the optimal approach, but it would be a good start.

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/1ed760e1-2cc4-44c7-995d-8c47f9a56073)
Thank you for your answer. When browsing 3D Gaussian, especially oblique photography data, it appears very blurry from a distance, indicating a problem with the rendering algorithm. If it is close to rendering, it is almost similar to web-based rendering.

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/9464ffb4-4b28-4293-8e65-0d7e6510fff9)
The following image is a 3D Gaussian using web browsing.
https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php

**Comment by chenqi13814529300** [comment]
> 很好的功能请求，不确定我能否很快得到它。我的理解是 2DGS 是 3DGS 的一个特例，可以将 3DGS 的比例因子沿一个维度设置为零 （0.00001），而现有的 3DGS 渲染器_应该_可以正常工作。然而，我认为这不是最佳方法，但这将是一个好的开始。


I have achieved this effect, it is indeed simple, I really admire you.

**Comment by chenqi13814529300** [comment]
> Good feature request, not sure I can get to it anytime soon. My understanding tho is that 2DGS is a special case of 3DGS, it might be possible to just set the scale factor of the 3DGS to be zero (0.00001) along one dimension, and the existing 3DGS renderer _should_ just work. However I don't think this would be the optimal approach, but it would be a good start.

I have achieved this effect, it is indeed simple, I really admire you.

**Comment by hyperlogic** [comment]
What was the final result, did you get this working?

**Comment by chenqi13814529300** [comment]
> What was the final result, did you get this working?

Can work normally. But there is a problem, whether it is 2D or 3D rendering, the remote visualization effect is very poor.
![image](https://github.com/user-attachments/assets/6f2a27b5-08de-4ed1-8b40-3c74c1deebb3)

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/6b180cbc-4bf5-413c-a3aa-e71f4a592024)
Hello, after using this parameter, the distance is similar to other renderers. Thank you for your effort.
