### ISSUE TITLE
Visual fluency

### ISSUE THREAD

**Issue by chenqi13814529300** [hyperlogic/splatapult#33]
Hello, I have noticed that when the scene is slightly larger and the video memory usage is around 5G (my 4090), moving the scene position left and right can cause a bit of lag. Is there any way to solve this problem?

**Comment by chenqi13814529300** [comment]
At a slightly closer distance, the FPS is high, but at a distance, the FPS is low and the visualization effect is poor (compared to web-based visualization algorithms such as superSplat). It shouldn't be due to the sorting algorithm, it seems to be a rendering issue.

**Comment by chenqi13814529300** [comment]
The urgent task now is to increase the smoothness of visualization. In the same large-scale scene, when viewed from a medium to long distance, SuperSplat browsing is obviously smooth. It's not C++, why is it so smooth?

**Comment by hyperlogic** [comment]
What OS are you using? Linux or Windows? I noticed an similar issue on Linux w.r.t. large scenes, where Windows did not have this issue.

Anyhow, I'm not sure what SuperSplat is doing, but I think they are using the WebGPU API, not WebGL.  This means they are using a more "modern" API that may not have the same issues as older OpenGL based APIs.  Specifically, the copying of buffers from compute shaders (for radix sort) to the rendering side. I'd like to try to port splatapult to Vulkan, but it's not something I can get to soon.

**Comment by chenqi13814529300** [comment]
Thank you for your answer. I am using Windows, and the data visualization browsing at around 2GB is indeed quite laggy. The web version is not laggy. Personally, I am still quite confused, maybe it is a problem with my computer.
