### ISSUE TITLE
question about this convolution

### ISSUE THREAD

**Issue by yuyaolong** [hyperlogic/splatapult#34]
https://github.com/hyperlogic/splatapult/blob/e87960fdf4a56fa7f12e254e225b4ed5b6461c2f/shader/splat_vert.glsl#L195

Hi Anthony,
Why we need to add fixed number 0.3f here? I also saw this in original 3DGS cuda version computeCov2D.
Could you explain more this?

Thanks

**Comment by hyperlogic** [comment]
I couldn't find this in the 3dgs paper but maybe its from the EWA Splatting paper. Anyhow, this applies a low pass filter to the Gaussian in screen space, basically giving us anti-aliasing for free.  The 0.3 is a bit arbitrary.  0.5 makes things a bit too blurry and 0.1 makes skinny Gaussian splats "shimmer" when moving the camera.

**Comment by yuyaolong** [comment]
Yeah. It's mentioned in EWA projection matrix section "4.5 Integration and Band-Limiting".
![image](https://github.com/user-attachments/assets/defa358c-2d90-43a2-b574-da442b96206d)

Someone give a guess reason about number 0.3 in inria repo [here ](https://github.com/graphdeco-inria/diff-gaussian-rasterization/issues/14?u=http://github.com/interestingLSY/diff-gaussian-rasterization/commit/989320fdf2563dc06bef852dc78ebd2cf820c5ba)
from my understanding
1. mathematically: the convolution calculation between low-pass filter gaussian kernel and original gaussian is end up with covariance matrix add.
2. intuitively: basically make original gaussian ellipse more "fat" (make the eigenvalue of covariance matrix bigger which is the major axis and minor axis of the ellipse)
3. agree, probably the 0.3f is magic number that has been tried out.
