### ISSUE TITLE
about issues with glm

### ISSUE THREAD

**Issue by lintianfang** [hyperlogic/splatapult#35]
Does anyone meet this issue when cmake the project:

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

The glm_DIR cannnot be found, and there is no glmConfig.cmake file in the folder.

Thank you very much!

**Comment by hyperlogic** [comment]
Hi, I'm not sure how you are building this and on what platform.
First I would look at [BUILD.md](https://github.com/hyperlogic/splatapult/blob/main/BUILD.md) which uses vcpkg to download all the dependencies, including glm.

If you are using the system provided glm, which should be available via apt-get libglm-dev, you may have to set a CMAKE_PREFIX_DIR in the command line for cmake.

**Comment by lintianfang** [comment]
> Hi, I'm not sure how you are building this and on what platform. First I would look at [BUILD.md](https://github.com/hyperlogic/splatapult/blob/main/BUILD.md) which uses vcpkg to download all the dependencies, including glm.
> 
> If you are using the system provided glm, which should be available via apt-get libglm-dev, you may have to set a CMAKE_PREFIX_DIR in the command line for cmake.

Thank you very much! Now I solve it, I uses Windows and vcpkg. Before that, the vcpkg path cannot be found, I add the absolute path for it, now it solved.
