### ISSUE TITLE
[ERROR] Failed to load vertex shader shader/debugdraw_vert.glsl

### ISSUE THREAD

**Issue by lintianfang** [hyperlogic/splatapult#36]
PS D:\codes\splatapult\Release> .\splatapult.exe D:\data\greenplant\pepe_md.ply
[ERROR] Failed to load vertex shader shader/debugdraw_vert.glsl
[ERROR] Error loading DebugRenderer shader!
[ERROR] DebugRenderer Init failed
[ERROR] App::Init failed

When I run the .exe, i got this issue, do you know how to solve it?

I am working on Win11.

Thank you very much!

**Comment by hyperlogic** [comment]
Hi, depending on how you built it, it will search for the shaders in the following places:
builds with SHIPPING defined will look for "shader/", non SHIPPING builds will look in "../../shader/"
The idea is that while you are developing you can run the exe from the build/Debug or build/Release dirs.

**Comment by lintianfang** [comment]
Thank you very much! The issue was solved.
